# Generated by Django 3.1.7 on 2021-03-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='available',
            new_name='avaibles',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='id',
        ),
        migrations.AlterField(
            model_name='guide',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_name',
            field=models.CharField(max_length=100),
        ),
    ]
