# Generated by Django 3.1.7 on 2021-04-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20210401_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='available',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guide',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='guide',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
