# Generated by Django 3.1.7 on 2021-03-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='current_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('sub_district_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='destination_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('sub_district_name', models.CharField(max_length=100)),
            ],
        ),
    ]
