# Generated by Django 3.1.7 on 2021-04-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
