# Generated by Django 3.1.7 on 2021-04-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0004_auto_20210401_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air',
            name='time',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='time',
        ),
        migrations.RemoveField(
            model_name='train',
            name='time',
        ),
        migrations.AlterField(
            model_name='air',
            name='air_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_name',
            field=models.CharField(max_length=150),
        ),
    ]
