# Generated by Django 3.1.7 on 2021-04-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0005_auto_20210408_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='air',
            name='date_time',
            field=models.CharField(default='SOME STRING', max_length=150),
        ),
        migrations.AddField(
            model_name='bus',
            name='date_time',
            field=models.CharField(default='SOME STRING', max_length=150),
        ),
        migrations.AddField(
            model_name='train',
            name='date_time',
            field=models.CharField(default='SOME STRING', max_length=150),
        ),
    ]
