# Generated by Django 3.1.7 on 2021-04-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('full_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('password', models.IntegerField()),
            ],
        ),
    ]
